### PR TITLE
PHP7 support improvements

### PR DESCRIPTION
**Pull request by Sannis**

### CODE REVIEW

**Comment by krakjoe** [comment]
Can't merge from phone, will be home in an hour ... If anyone else can merge please do it ...@bwoebi ?

**Comment by krakjoe** [comment]
Excellent work by the way, thanks ;)

**Comment by krakjoe** [comment]
You can merge yourself ... Please continue PRS beforeerging ;)

**Comment by Sannis** [comment]
There is no any rush to merge it immediately, @krakjoe :-)

**Comment by krakjoe** [comment]
Still, feel free to merge it yourself, or one of us will do it later ... You have push acess

**Comment by Sannis** [comment]
Thanks for your trust

**Pull request merged**
