### PR TITLE
Directly accessing op_array.static_variables is no longer supported

### PR DESCRIPTION
**Pull request by cmb69**
As of PHP 7.4.0, immutable op_arrays are no longer copied to process
memory.  op_array.static_variables may refer to mutable data in the
process memory, though, so we have to use the indirection offered via
the `ZEND_MAP_PTR_*()` macros to reliably get at the desired data.

### CODE REVIEW

**Comment by cmb69** [comment]
-5 failing tests, but I'm not sure whether I'm using the `ZEND_MAP_PTR_*()` API correctly.

**Comment by cmb69** [comment]
Oh, almost forgot that this needs overhaul.

**Comment by krakjoe** [comment]
@cmb69 if you want to take another look at this, I hope to do a release soon-ish ...

merge when ready ...

**Comment by krakjoe** [comment]
Fixed in d4aa3d39264c8ae7cb755a2b50f9c872867714fb

**Pull request closed without merging**
