### PR TITLE
Add 7.2 testing and allow nightlies to fail.

### PR DESCRIPTION
**Pull request by SMillerDev**

### CODE REVIEW

**Comment by SMillerDev** [comment]
@krakjoe anything I can do to improve this PR?

**Comment by cmb69** [comment]
@SMillerDev I would remove the PHP 7.0 build, since [this version is EOL'd](http://php.net/supported-versions.php).

**Comment by RyanHartje** [comment]
Would love to see 7.2 testing supported.

**Comment by SMillerDev** [comment]
Updated for 7.3 @krakjoe

**Comment by krakjoe** [comment]
I missed this, but the travis file looks like it should now ... sorry about the delay ...

**Pull request closed without merging**
